[scraper]
periodMinutes = 1
verbose = true

[[sensor]]
id=1
name="The important one"
url="http://localhost:8080/ping"
jsonPath="pong.ping"

[[sensor]]
#the failing one
ID=2
Name="Another"
URL="http://localhost:9999/data"
JSONPath="data.value"
